import { formatGoogleCalendarDisplayName, isLikelyAutoGeneratedCalendarLabel } from "@/lib/google-calendar-display";
import { NextResponse } from "next/server";
import { requireSession } from "@/lib/api/require-session";
import { fetchGoogleCalendarListDisplayNamesById, fetchGoogleCalendarSummariesById } from "@/server/calendar";
import { prisma } from "@/server/db";

export const runtime = "nodejs";

function calendarDisplayQuality(calendarId: string, label: string): number {
  const name = label.trim();
  if (!name) return 0;
  if (isLikelyAutoGeneratedCalendarLabel(calendarId, name)) return 1;
  return 2;
}

/**
 * Classifier UI: calendar list and color ids (DB cache; names enriched via calendars.get / calendarList when needed).
 */
export async function GET() {
  const session = await requireSession();
  if ("response" in session) return session.response;

  const rows = await prisma.googleCalendarEventCache.findMany({
    where: { userId: session.user.id, isCancelled: false },
    orderBy: { updatedAt: "desc" },
    take: 2000,
    select: {
      calendarId: true,
      calendarName: true,
      calendarColorId: true,
      eventColorId: true,
    },
  });

  const calById = new Map<string, { calendarId: string; calendarName: string; calendarColorId: string }>();
  const colorIds = new Set<string>();
  for (const r of rows) {
    const candidate = formatGoogleCalendarDisplayName(r.calendarId, r.calendarName);
    const calendarColorId = r.calendarColorId ?? "";
    const eventColorId = r.eventColorId ?? "";
    const existing = calById.get(r.calendarId);
    if (!existing) {
      calById.set(r.calendarId, { calendarId: r.calendarId, calendarName: candidate, calendarColorId });
    } else {
      if (calendarDisplayQuality(r.calendarId, candidate) > calendarDisplayQuality(r.calendarId, existing.calendarName)) {
        existing.calendarName = candidate;
      }
      if (!existing.calendarColorId && calendarColorId) {
        existing.calendarColorId = calendarColorId;
      }
    }
    const effective = eventColorId || calendarColorId;
    if (effective) colorIds.add(effective);
  }

  const calendars = Array.from(calById.values());
  const needSummaries = calendars
    .filter((c) => isLikelyAutoGeneratedCalendarLabel(c.calendarId, c.calendarName))
    .map((c) => c.calendarId);
  const summaries = await fetchGoogleCalendarSummariesById(session.user.id, needSummaries);
  for (const c of calendars) {
    const s = summaries.get(c.calendarId);
    if (s) c.calendarName = s;
  }

  const stillWeak = calendars.filter((c) => isLikelyAutoGeneratedCalendarLabel(c.calendarId, c.calendarName));
  if (stillWeak.length) {
    const fromList = await fetchGoogleCalendarListDisplayNamesById(
      session.user.id,
      stillWeak.map((c) => c.calendarId),
    );
    for (const c of calendars) {
      const n = fromList.get(c.calendarId);
      if (!n?.trim()) continue;
      if (calendarDisplayQuality(c.calendarId, n) > calendarDisplayQuality(c.calendarId, c.calendarName)) {
        c.calendarName = n;
      }
    }
  }

  return NextResponse.json({
    calendars: calendars.sort((a, b) => a.calendarName.localeCompare(b.calendarName)),
    colorIds: Array.from(colorIds.values()).sort(),
  });
}
