/**
 * Google Calendar の calendarId がそのまま UI に出るのを避け、短く読みやすいラベルにする。
 */

/**
 * API / iCal の X-WR-CALNAME などで、実質プレースホルダーになる短い summary が返ることがある。
 * その場合は calendarId から人間向けラベルを組み立て直す。
 */
export function isTrivialGoogleCalendarSummary(summary: string): boolean {
  const t = summary.trim().toLowerCase();
  if (!t) return true;
  if (t.length === 1) return true;
  return new Set([
    "date",
    "dates",
    "calendar",
    "calendars",
    "events",
    "event",
    "schedule",
    "ical",
    "ics",
    "untitled",
    "無題",
  ]).has(t);
}

/** Label likely needs calendars.get (calendarList summary missing or generic). */
export function isLikelyAutoGeneratedCalendarLabel(calendarId: string, displayName: string): boolean {
  const id = calendarId.trim();
  const name = displayName.trim();
  if (!name) return true;
  if (isTrivialGoogleCalendarSummary(name)) return true;
  if (name === id) return true;
  if (humanizeGoogleCalendarId(id) === name) return true;
  if (name.startsWith("取り込みカレンダー（") || name.startsWith("共有カレンダー（")) return true;
  if (name.startsWith("Google 公式（")) return true;
  const lowerId = id.toLowerCase();
  if (lowerId.includes("@group.v.calendar.google.com")) return true;
  if (lowerId.includes("#holiday@")) return true;
  return false;
}

export function humanizeGoogleCalendarId(calendarId: string): string {
  const id = calendarId.trim();
  if (!id) return "カレンダー";
  const lower = id.toLowerCase();
  if (id === "primary" || lower === "primary") return "メインカレンダー";

  const stripSuffix = (suffixLower: string): string | null => {
    if (!lower.endsWith(suffixLower)) return null;
    return id.slice(0, id.length - suffixLower.length);
  };

  /** 祝日など（ja.japanese#holiday@group.v.calendar.google.com） */
  const holidayLocal = stripSuffix("@group.v.calendar.google.com");
  if (holidayLocal !== null) {
    const l = holidayLocal.toLowerCase();
    if (l.includes("#holiday") || l.includes("holiday")) {
      if (l.startsWith("ja.") || l.includes("japanese")) return "日本の祝日";
      return "祝日カレンダー";
    }
    return `Google 公式（${shortCalKey(holidayLocal)}）`;
  }

  const groupLocal = stripSuffix("@group.calendar.google.com");
  if (groupLocal !== null) {
    return `共有カレンダー（${shortCalKey(groupLocal)}）`;
  }

  const importLocal = stripSuffix("@import.calendar.google.com");
  if (importLocal !== null) {
    return `取り込みカレンダー（${shortCalKey(importLocal)}）`;
  }

  const at = id.indexOf("@");
  if (at > 0) {
    const local = id.slice(0, at);
    const domain = id.slice(at + 1);
    if (local.length >= 20) {
      return `${domain}（${shortCalKey(local)}）`;
    }
    return `${local}@${domain}`;
  }

  if (id.length > 32) return `${id.slice(0, 12)}…${id.slice(-6)}`;
  return id;
}

function shortCalKey(s: string): string {
  const t = s.trim();
  if (t.length <= 10) return t || "—";
  return `${t.slice(0, 4)}…${t.slice(-4)}`;
}

/** Label likely needs calendars.get (calendarList summary missing or generic). */
export function displayNameFromGoogleCalendarListEntry(item: {
  id?: string | null;
  summary?: string | null;
  summaryOverride?: string | null;
  description?: string | null;
}): string {
  const id = item.id?.trim() ?? "";
  if (!id) return "カレンダー";
  const rawCandidate =
    item.summaryOverride?.trim() ||
    item.summary?.trim() ||
    item.description?.trim() ||
    "";
  const raw =
    rawCandidate && !isTrivialGoogleCalendarSummary(rawCandidate) && rawCandidate !== id ? rawCandidate : "";
  if (raw) return raw;
  return humanizeGoogleCalendarId(id);
}

/** DB の calendarName が空・ID と同一（旧同期）のときのフォールバック */
export function formatGoogleCalendarDisplayName(
  calendarId: string,
  calendarName: string | null | undefined,
): string {
  const id = calendarId.trim();
  const raw = (calendarName ?? "").trim();
  if (raw && !isLikelyAutoGeneratedCalendarLabel(id, raw)) return raw;
  return humanizeGoogleCalendarId(id);
}
